apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.app.name}}-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
type: Opaque
data:
  username: c2VydmljZQo=
  password: cGFzc3dvcmQK
  DATABASE_URI: cG9zdGdyZXNxbCthc3luY3BnOi8vc2VydmljZTpwYXNzd29yZEBwb3N0Z3Jlcy1kYXRhYmFzZS1wb3N0Z3Jlc3FsOjU0MzIvdXNlcl90ZXN0X2RiCg==